import {
  Music, Music2, Film, Disc3, Tv, Star, Gamepad2, Megaphone, Car, Puzzle,
  Radio, Shirt, Clapperboard, Trophy,
  Landmark, Building, PawPrint, Globe, Utensils, Lightbulb, Flag, Heart,
  Building2, Atom, Telescope, BookOpen, Waves, Piano,
  Shuffle, Quote, SpellCheck, Network, Hash, Search, UserX, ArrowUpDown, Lock,
  Equal, HelpCircle, ArrowLeftRight, BookMarked, CircleHelp, GraduationCap, MessageSquare,
  Layers, Eye, CircleOff, Shapes, Palette, Grid3x3, Move, Zap, Link2,
  Image, Users, Ban, Brain, RotateCcw, Asterisk, Dices, Sun,
  CheckCircle, Clock, Smile, Wrench, MessageCircle, PenTool, HeartHandshake,
  HelpingHand, ScrollText, Scale, CalendarRange, Clapperboard as Clapperboard2,
  Castle, Languages,
  BookOpenText, Binary, UserCheck, PenLine, FlaskConical, UsersRound,
  MonitorPlay, Beaker, BrainCircuit, Link,
  Target, Hourglass, CircleDot, Package, Scroll, Calculator, Award,
  Volume2, Crosshair, ListOrdered, Bomb,
  Mic, CalendarDays, MessageSquareQuote, Church, History, FileSearch, Medal, Sparkles,
  MonitorSmartphone, CookingPot, Tent, Lasso,
  Bird, Flower2, MapPin, CloudLightning,
  BookType, Combine, FileText, PencilLine,
  ArrowDown01, FastForward, FolderTree, ShieldQuestion, Ear, Repeat, BookHeart, Armchair, Map, Timer,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  // Nostalgia Trivia
  "fifties-nostalgia": Music,
  "sixties-music": Music2,
  "classic-hollywood": Film,
  "seventies-nostalgia": Disc3,
  "classic-tv": Tv,
  "sixties-nostalgia": Star,
  "eighties-nostalgia": Gamepad2,
  "classic-commercials": Megaphone,
  "classic-cars": Car,
  "vintage-toys": Puzzle,
  "classic-radio": Radio,
  "decade-fashions": Shirt,
  "classic-cartoons": Clapperboard,
  "classic-sports": Trophy,

  // General Knowledge
  "famous-landmarks": Landmark,
  "us-presidents": Building,
  "nature-animals": PawPrint,
  "geography-challenge": Globe,
  "food-cooking": Utensils,
  "science-inventions": Lightbulb,
  "american-history": Flag,
  "human-body-health": Heart,
  "world-capitals": Building2,
  "famous-scientists": Atom,
  "space-astronomy": Telescope,
  "famous-literature": BookOpen,
  "world-oceans-rivers": Waves,
  "musical-instruments": Piano,

  // Word Games
  "word-scramble": Shuffle,
  "complete-the-proverb": Quote,
  "spelling-bee": SpellCheck,
  "word-association": Network,
  "crossword-classic": Hash,
  "word-search": Search,
  "hangman": UserX,
  "word-ladder": ArrowUpDown,
  "cryptogram": Lock,
  "synonym-challenge": Equal,
  "whats-the-word": HelpCircle,
  "antonym-challenge": ArrowLeftRight,
  "idiom-origins": BookMarked,
  "rhyme-time": Music,
  "commonly-confused": CircleHelp,
  "vocabulary-builder": GraduationCap,
  "figures-of-speech": MessageSquare,

  // Memory Games
  "memory-card-match": Layers,
  "spot-the-difference": Eye,
  "whats-missing": CircleOff,
  "pattern-recognition": Shapes,
  "color-shape-sorting": Palette,
  "sudoku-puzzles": Grid3x3,
  "sliding-puzzle": Move,
  "sequence-memory": Zap,
  "matching-pairs": Link2,
  "picture-quiz": Image,
  "famous-faces": Users,
  "odd-one-out": Ban,
  "trivia-recall": Brain,
  "visual-clues": Eye,
  "before-and-after": ArrowLeftRight,
  "connection-puzzle": Puzzle,
  "math-challenge": Hash,

  // Additional Word Games
  "anagram-challenge": RotateCcw,
  "missing-vowels": Asterisk,

  // Additional Nostalgia Trivia
  "classic-board-games": Dices,

  // Additional General Knowledge
  "world-religions-mythology": Sun,

  // New games
  "true-or-false": CheckCircle,
  "timeline-sort": Clock,
  "emoji-decoder": Smile,
  "famous-inventions": Wrench,
  "classic-sitcom-catchphrases": MessageCircle,
  "grammar-punctuation": PenTool,
  "famous-couples": HeartHandshake,

  // Batch 8 games
  "who-am-i": HelpingHand,
  "riddle-challenge": ScrollText,
  "nostalgia-fact-or-fiction": Scale,
  "decade-sorting": CalendarRange,
  "classic-movie-quotes": Clapperboard2,
  "ancient-modern-wonders": Castle,
  "foreign-words": Languages,

  // Batch 9 games
  "famous-first-lines": BookOpenText,
  "number-memory": Binary,
  "nostalgia-who-am-i": UserCheck,
  "grammar-true-or-false": PenLine,
  "science-sorting": FlaskConical,
  "famous-duos": UsersRound,
  "retro-tv-themes": MonitorPlay,
  "everyday-science": Beaker,
  "brain-teasers": BrainCircuit,
  "word-connections": Link,

  // Batch 10 games
  "estimation-game": Target,
  "history-timeline": Hourglass,
  "memory-true-or-false": CircleDot,
  "what-am-i": Package,
  "world-history": Scroll,
  "math-numbers": Calculator,
  "retro-movie-stars": Award,
  "classic-jingles": Volume2,
  "concentration-quiz": Crosshair,
  "number-patterns": ListOrdered,
  "minesweeper": Bomb,

  // Batch 11 games
  "finish-the-lyric": Mic,
  "name-the-decade": CalendarDays,
  "famous-quotes": MessageSquareQuote,
  "bible-knowledge": Church,
  "old-time-expressions": History,
  "word-origins": FileSearch,
  "famous-firsts": Medal,
  "logic-deduction": Sparkles,

  // Batch 12 games
  "classic-game-shows": MonitorSmartphone,
  "classic-diners-drive-ins": CookingPot,
  "woodstock-music-festivals": Tent,
  "classic-westerns": Lasso,
  "birds-birdwatching": Bird,
  "flowers-gardening": Flower2,
  "travel-geography-usa": MapPin,
  "weather-natural-phenomena": CloudLightning,
  "proverbs-sayings": BookType,
  "compound-words": Combine,
  "abbreviations-acronyms": FileText,
  "complete-the-phrase": PencilLine,
  "sequence-order": ArrowDown01,
  "what-comes-next": FastForward,
  "category-sort": FolderTree,
  "two-truths-one-lie": ShieldQuestion,
  "remember-the-year": Clock,
  "everyday-memory-test": Eye,

  // Batch 13 — 25 new games
  "crossword-nature-science": Hash,
  "word-search-animals": Search,
  "food-word-scramble": Shuffle,
  "cryptogram-poetry": Lock,
  "word-ladder-challenge": ArrowUpDown,
  "nostalgia-hangman": UserX,
  "nostalgia-riddles": ScrollText,
  "vintage-spelling-bee": SpellCheck,
  "old-time-sayings": Quote,
  "retro-word-association": Network,
  "nostalgia-matching": Link2,
  "nostalgia-estimation": Target,
  "science-true-or-false": CheckCircle,
  "what-in-the-world": Globe,
  "inventions-timeline": Hourglass,
  "animal-kingdom-sorting": PawPrint,
  "mental-math": Calculator,
  "logic-patterns": Shapes,
  "observation-challenge": Eye,
  "nature-card-match": Layers,
  "color-sequence-challenge": Zap,
  "number-recall-challenge": Binary,
  "whats-changed": CircleOff,
  "sudoku-challenge": Grid3x3,
  "sliding-puzzle-challenge": Move,

  // Batch 14 — 10 new games
  "homophones-challenge": Ear,
  "double-meanings": Repeat,
  "history-spelling-bee": SpellCheck,
  "word-search-travel": Map,
  "classic-childrens-books": BookHeart,
  "vintage-household-items": Armchair,
  "famous-speeches": Mic,
  "geography-sorting": Globe,
  "famous-pairs-matching": Link2,
  "rapid-recall": Timer,

  // Batch 15 — Word Games (25 quizzes)
  "prefix-suffix-quiz": PenTool,
  "literary-vocabulary": BookOpen,
  "word-pairs-quiz": Link2,
  "british-american-english": Languages,
  "silent-letters-quiz": Volume2,
  "onomatopoeia-quiz": Megaphone,
  "palindromes-quiz": RotateCcw,
  "root-words-quiz": FolderTree,
  "collective-nouns-quiz": Users,
  "eponyms-quiz": UserCheck,
  "portmanteau-words": Combine,
  "archaic-words": Scroll,
  "contronyms-quiz": ArrowLeftRight,
  "animal-idioms": PawPrint,
  "color-expressions": Palette,
  "weather-expressions": CloudLightning,
  "food-expressions": Utensils,
  "music-vocabulary": Music2,
  "legal-vocabulary": Scale,
  "medical-vocabulary": Heart,
  "nautical-terms": Waves,
  "sports-lingo": Trophy,
  "kitchen-vocabulary": CookingPot,
  "travel-vocabulary": MapPin,
  "nature-vocabulary": Flower2,

  // Batch 15 — Nostalgia Trivia (25 quizzes)
  "classic-candy": Star,
  "vintage-advertisements": Megaphone,
  "retro-technology": MonitorSmartphone,
  "classic-dance-crazes": Music,
  "old-school-playground": Smile,
  "vintage-comic-strips": BookOpen,
  "classic-theme-parks": Castle,
  "retro-fashion-icons": Shirt,
  "classic-radio-shows": Radio,
  "vintage-appliance-brands": Wrench,
  "classic-olympic-moments": Medal,
  "retro-slang": MessageCircle,
  "classic-department-stores": Building2,
  "vintage-car-models": Car,
  "classic-variety-shows": Tv,
  "vintage-home-decor": Armchair,
  "classic-cereal-brands": Package,
  "retro-hairstyles": Sparkles,
  "classic-detective-shows": Search,
  "vintage-kitchen-brands": CookingPot,
  "classic-family-sitcoms": Users,
  "retro-school-days": GraduationCap,
  "vintage-holiday-traditions": CalendarDays,
  "classic-soap-operas": Film,
  "famous-tv-catchphrases": MessageSquareQuote,

  // Batch 15 — General Knowledge (25 quizzes)
  "world-currencies": Landmark,
  "national-symbols": Flag,
  "famous-explorers": Globe,
  "world-languages": Languages,
  "famous-buildings": Building,
  "precious-gems": Sparkles,
  "world-festivals": Sun,
  "famous-battles": Trophy,
  "olympic-sports": Medal,
  "famous-artists": Palette,
  "ancient-civilizations": Castle,
  "famous-bridges": Link,
  "classical-music": Piano,
  "famous-women-history": Award,
  "famous-ships": Waves,
  "nutrition-health": Heart,
  "astronomy-facts": Telescope,
  "world-flags": Flag,
  "world-dances": Music,
  "inventions-by-decade": Lightbulb,
  "world-cuisine": Utensils,
  "famous-monuments": Landmark,
  "earth-science": Atom,
  "mythology-legends": ScrollText,
  "famous-libraries-museums": BookOpen,

  // Batch 15 — Memory Games (25 quizzes)
  "historical-dates": CalendarDays,
  "flag-identification": Flag,
  "animal-classification": PawPrint,
  "element-symbols": Atom,
  "state-capitals-recall": Building2,
  "famous-paintings": Image,
  "roman-numerals": Hash,
  "measurement-conversions": Calculator,
  "acronym-recall": FileText,
  "phobia-names": HelpCircle,
  "zodiac-trivia": Star,
  "birthstone-quiz": Sparkles,
  "color-mixing-quiz": Palette,
  "speed-math-quiz": Zap,
  "reverse-trivia": RotateCcw,
  "decade-music-recall": Music2,
  "movie-year-quiz": Film,
  "presidential-order": ListOrdered,
  "science-facts-recall": FlaskConical,
  "famous-logos": Eye,
  "world-records": Trophy,
  "brain-facts": BrainCircuit,
  "visual-memory-quiz": Image,
  "association-challenge": Network,
  "quick-thinking": Zap,

  // Batch 16 — Word Games (25 quizzes)
  "alliteration-quiz": PenLine,
  "oxymorons-quiz": ArrowLeftRight,
  "similes-quiz": Equal,
  "metaphors-quiz": MessageSquare,
  "tongue-twisters-quiz": Mic,
  "shakespeare-words": BookOpen,
  "french-loanwords": Languages,
  "latin-phrases": Scroll,
  "business-jargon": Building2,
  "technology-terms": MonitorSmartphone,
  "art-vocabulary": Palette,
  "fashion-vocabulary": Shirt,
  "astronomy-vocabulary": Telescope,
  "body-idioms": Heart,
  "number-expressions": Hash,
  "time-expressions": Clock,
  "money-expressions": Calculator,
  "war-expressions": Target,
  "book-vocabulary": BookOpen,
  "garden-vocabulary": Flower2,
  "ocean-vocabulary": Waves,
  "mountain-vocabulary": Landmark,
  "desert-vocabulary": Sun,
  "mythology-words": Castle,
  "geography-vocabulary": Globe,

  // Batch 16 — Nostalgia Trivia (25 quizzes)
  "classic-country-music": Music,
  "vintage-board-games": Dices,
  "retro-candy-bars": Star,
  "classic-sitcom-families": Users,
  "vintage-movie-theaters": Film,
  "retro-arcade-games": Gamepad2,
  "classic-childrens-tv": Tv,
  "vintage-soda-brands": CookingPot,
  "retro-dance-moves": Music2,
  "classic-spy-movies": Search,
  "vintage-record-players": Disc3,
  "classic-disco-era": Sparkles,
  "vintage-ice-cream": Smile,
  "retro-drive-in-movies": Car,
  "classic-rock-bands": Music,
  "vintage-diners": Utensils,
  "retro-roller-skating": RotateCcw,
  "classic-war-movies": Trophy,
  "vintage-typewriters": PenTool,
  "retro-station-wagons": Car,
  "classic-folk-music": Music2,
  "vintage-photography": Image,
  "retro-jukeboxes": Volume2,
  "classic-musicals": Clapperboard,
  "classic-westerns-tv": Lasso,

  // Batch 16 — General Knowledge (25 quizzes)
  "desert-landscapes": Sun,
  "volcanic-wonders": Atom,
  "famous-rivers": Waves,
  "island-nations": Globe,
  "mountain-ranges": Landmark,
  "famous-gardens": Flower2,
  "famous-castles": Castle,
  "ancient-empires": Scroll,
  "famous-treaties": FileText,
  "famous-philosophers": Brain,
  "nobel-prize-winners": Award,
  "famous-architects": Building,
  "famous-composers": Piano,
  "periodic-table": Atom,
  "human-anatomy": Heart,
  "famous-photographers": Image,
  "world-waterfalls": Waves,
  "famous-poets": BookOpen,
  "world-islands": Globe,
  "famous-economists": Calculator,
  "world-mountains": Landmark,
  "famous-mathematicians": Hash,
  "world-religions": Sun,
  "famous-inventions-history": Lightbulb,
  "world-capitals-advanced": Building2,

  // Batch 16 — Memory Games (25 quizzes)
  "country-capitals-quiz": Globe,
  "periodic-element-quiz": Atom,
  "famous-inventions-recall": Lightbulb,
  "world-leaders-quiz": Users,
  "landmark-locations": MapPin,
  "animal-sounds-quiz": PawPrint,
  "famous-quotes-recall": MessageSquareQuote,
  "historical-figures": Clock,
  "planet-facts-quiz": Telescope,
  "ocean-creatures-quiz": Waves,
  "famous-composers-recall": Piano,
  "currency-countries": Landmark,
  "language-origins-quiz": Languages,
  "famous-authors-recall": BookOpen,
  "sports-records-quiz": Trophy,
  "food-origins-quiz": Utensils,
  "famous-discoveries": FlaskConical,
  "music-decades-quiz": Music2,
  "geography-extremes": Globe,
  "famous-nicknames": UserCheck,
  "unit-conversions": Calculator,
  "word-definitions-quiz": BookMarked,
  "number-facts-quiz": Hash,
  "science-symbols-quiz": Atom,
  "famous-duos-recall": UsersRound,

  // Batch 17 — Word Games (25 quizzes)
  "spoonerisms-quiz": Shuffle,
  "malapropisms-quiz": CircleHelp,
  "cockney-rhyming-slang": MessageCircle,
  "australian-slang": Globe,
  "southern-expressions": Sun,
  "theater-vocabulary": Clapperboard,
  "wine-vocabulary": Utensils,
  "architecture-terms": Building,
  "music-theory-terms": Music2,
  "photography-terms": Image,
  "cooking-techniques": CookingPot,
  "dance-vocabulary": Music,
  "geology-vocabulary": Landmark,
  "aviation-terms": Zap,
  "botanical-terms": Flower2,
  "zoology-terms": PawPrint,
  "archaeology-terms": Search,
  "printing-terms": FileText,
  "maritime-expressions": Waves,
  "horse-riding-terms": Trophy,
  "chess-vocabulary": Grid3x3,
  "textile-terms": Shirt,
  "weather-vocabulary": CloudLightning,
  "irish-expressions": Languages,
  "scottish-words": Languages,

  // Batch 17 — Nostalgia Trivia (25 quizzes)
  "classic-jazz-music": Music2,
  "vintage-television-ads": Tv,
  "retro-camping-outdoors": Tent,
  "classic-romance-movies": Heart,
  "vintage-trains": Car,
  "retro-toys-dolls": Puzzle,
  "classic-horror-movies": Film,
  "vintage-newspapers": FileText,
  "retro-bicycles": RotateCcw,
  "classic-comedy-duos": Smile,
  "vintage-jewelry-fashion": Sparkles,
  "classic-christmas-specials": Star,
  "retro-beach-culture": Sun,
  "classic-animated-movies": Clapperboard,
  "vintage-kitchen-gadgets": Wrench,
  "classic-mystery-novels": Search,
  "retro-state-fairs": Award,
  "classic-swing-music": Music,
  "vintage-lunch-boxes": Package,
  "retro-drive-in-restaurants": Utensils,
  "classic-cartoon-characters": Smile,
  "vintage-postcards": Image,
  "retro-pet-trends": PawPrint,
  "classic-adventure-movies": Film,
  "vintage-radios": Radio,

  // Batch 17 — General Knowledge (25 quizzes)
  "world-heritage-sites": Landmark,
  "famous-trials": Scale,
  "world-canals": Waves,
  "famous-last-words": MessageSquareQuote,
  "world-caves": Globe,
  "famous-siblings": Users,
  "world-lakes": Waves,
  "famous-historical-events": Clock,
  "world-national-parks": Flower2,
  "famous-robberies": Lock,
  "space-exploration-missions": Telescope,
  "famous-hoaxes": CircleHelp,
  "famous-archaeological-finds": Search,
  "animal-kingdom-facts": PawPrint,
  "plant-kingdom-facts": Flower2,
  "ocean-depths": Waves,
  "climate-zones": Sun,
  "famous-escapes": Lock,
  "world-record-holders": Trophy,
  "famous-duels": Target,
  "world-trade-routes": Globe,
  "famous-codes-ciphers": Lock,
  "solar-system-facts": Telescope,
  "famous-feuds": Zap,
  "world-lighthouses": Lightbulb,

  // Batch 17 — Memory Games (25 quizzes)
  "state-flags-quiz": Flag,
  "bird-identification": Bird,
  "tree-identification": Flower2,
  "cloud-types-quiz": CloudLightning,
  "instrument-sounds-quiz": Piano,
  "gemstone-identification": Sparkles,
  "dog-breeds-quiz": PawPrint,
  "cat-breeds-quiz": PawPrint,
  "dinosaur-facts-quiz": Scroll,
  "space-missions-recall": Telescope,
  "vitamin-minerals-quiz": Heart,
  "bone-names-quiz": Brain,
  "organ-functions-quiz": Heart,
  "map-symbols-quiz": Globe,
  "art-movements-quiz": Palette,
  "fabric-types-quiz": Shirt,
  "car-logos-quiz": Car,
  "country-shapes-quiz": Globe,
  "famous-battles-recall": Trophy,
  "olympic-host-cities": Medal,
  "weather-symbols-quiz": CloudLightning,
  "music-notes-quiz": Music2,
  "dance-styles-quiz": Music,
  "world-capitals-extreme": Building2,
  "famous-paintings-recall": Image,

  // Batch 18 — Word Games (25 quizzes)
  "euphemisms-quiz": MessageSquare,
  "demonyms-quiz": Globe,
  "auto-antonyms": ArrowLeftRight,
  "words-from-names": UserCheck,
  "words-from-places": MapPin,
  "animal-group-names": PawPrint,
  "rhyming-pairs": Music,
  "false-friends": Languages,
  "old-english-words": Scroll,
  "spelling-rules": SpellCheck,
  "figurative-language": Quote,
  "verbal-reasoning": BrainCircuit,
  "language-trivia": Languages,
  "reduplication-words": Repeat,
  "medical-idioms": Heart,
  "word-play-quiz": PenLine,
  "vocabulary-in-context": BookMarked,
  "word-families": FolderTree,
  "word-associations-quiz": Network,
  "punctuation-quiz": PenTool,
  "borrowed-words": Languages,
  "backronyms-quiz": FileText,
  "word-length-quiz": ArrowUpDown,
  "tongue-trivia": Mic,
  "dysphemisms-quiz": MessageCircle,

  // Batch 18 — Nostalgia Trivia (25 quizzes)
  "classic-sci-fi-movies": Film,
  "vintage-cameras": Image,
  "retro-pinball-machines": Gamepad2,
  "classic-game-show-hosts": Tv,
  "retro-home-deliveries": Package,
  "classic-tv-theme-songs": Music2,
  "vintage-school-supplies": GraduationCap,
  "classic-tv-cowboys": Lasso,
  "vintage-toy-catalogs": Puzzle,
  "retro-prom-memories": Star,
  "classic-tv-detectives": Search,
  "retro-phone-history": MonitorSmartphone,
  "classic-movie-monsters": Clapperboard,
  "vintage-barbershops": Sparkles,
  "classic-tv-doctors": Heart,
  "vintage-gas-stations": Car,
  "retro-comic-books": BookOpen,
  "classic-tv-lawyers": Scale,
  "retro-summer-camps": Tent,
  "vintage-circus-carnival": Award,
  "retro-breakfast-cereals": CookingPot,
  "classic-tv-animals": PawPrint,
  "vintage-appliance-ads": Megaphone,
  "retro-sewing-crafts": Shirt,
  "vintage-travel-posters": Map,

  // Batch 18 — General Knowledge (25 quizzes)
  "famous-walls-barriers": Castle,
  "world-deserts-quiz": Sun,
  "famous-forgeries": Lock,
  "world-peninsulas": Globe,
  "accidental-inventions": Lightbulb,
  "world-straits": Waves,
  "famous-twins": Users,
  "world-rainforests": Flower2,
  "famous-expeditions": Map,
  "world-coral-reefs": Waves,
  "famous-first-flights": Zap,
  "world-geysers-springs": CloudLightning,
  "famous-food-origins": Utensils,
  "famous-medical-discoveries": FlaskConical,
  "world-glaciers": Landmark,
  "famous-predictions": Telescope,
  "world-plateaus": Globe,
  "famous-maps": Map,
  "world-archipelagos": Globe,
  "famous-museum-collections": Building,
  "world-fjords": Waves,
  "famous-unfinished-works": PenTool,
  "world-wetlands": Flower2,
  "famous-ghost-stories": ScrollText,
  "world-tidal-phenomena": Waves,

  // Batch 18 — Memory Games (25 quizzes)
  "flower-identification": Flower2,
  "butterfly-identification": Bird,
  "rock-types-quiz": Landmark,
  "constellation-quiz": Telescope,
  "insect-identification": Search,
  "herb-identification": Flower2,
  "spice-identification": CookingPot,
  "cheese-varieties-quiz": Utensils,
  "pasta-shapes-quiz": Utensils,
  "tea-varieties-quiz": CookingPot,
  "coffee-varieties-quiz": CookingPot,
  "fish-identification": Waves,
  "reptile-identification": PawPrint,
  "whale-dolphin-quiz": Waves,
  "mushroom-identification": Flower2,
  "berry-identification": Flower2,
  "nut-identification": Package,
  "wine-regions-quiz": MapPin,
  "famous-gardens-recall": Flower2,
  "famous-bridges-recall": Link,
  "famous-towers-quiz": Building,
  "famous-statues-quiz": Landmark,
  "world-currencies-recall": Calculator,
  "dog-breed-quiz": PawPrint,
};

export function GameIcon({
  gameId,
  color,
  size = 22,
}: {
  gameId: string;
  color: string;
  size?: number;
}) {
  const Icon = iconMap[gameId];
  if (!Icon) return null;

  return (
    <span
      className="mb-3 inline-flex h-10 w-10 items-center justify-center rounded-xl text-white"
      style={{ background: color }}
      aria-hidden="true"
    >
      <Icon size={size} strokeWidth={1.75} />
    </span>
  );
}

// Category colors
export const categoryColors: Record<string, string> = {
  "nostalgia-trivia": "#3B6FC0",
  "general-knowledge": "#0891B2",
  "word-games": "#E8983E",
  "memory-games": "#16A34A",
};
